### ISSUE TITLE
Website generation

### ISSUE THREAD

**Issue by babdab9** [KibiiTV/weebshare#19]
where the fuck is your code for the website?

**Comment by TemTemmie** [comment]
ask bin

**Comment by babdab9** [comment]
:man_facepalming: thas why I opened an issue... ffs

**Comment by binuwu** [comment]
magic

**Comment by binuwu** [comment]
actually it's hidden in DLLs and stuff, the token gen website is private for now.

**Comment by binuwu** [comment]
Precompiled ftw !!!

**Comment by binuwu** [comment]
static can be found in baka/wwwroot

**Comment by babdab9** [comment]
mmmhm
accept my invitation to my fork

**Comment by babdab9** [comment]
also, pr coming soon:tm:

**Comment by binuwu** [comment]
y tho

**Comment by binuwu** [comment]
and ok b4 u pr let me push new changes

**Comment by babdab9** [comment]
too l8
lemme cloze

**Comment by binuwu** [comment]
kk nvm u can pr now
