### ISSUE TITLE
iOS image preview doesn't like it

### ISSUE THREAD

**Issue by GummiWummiBear** [KibiiTV/weebshare#2]
Tapping the image results in a "Failed to load image error". Retrying doesn't help.
The only way to view the image in full quality is to tap the link and open in browser/in-app browser.

Probably some dumb stuff with embeds.

**Comment by binuwu** [comment]
tapping?

**Comment by binuwu** [comment]
Oh, that's a discord bug. Nothing to do with file-bin. Sorry!

**Comment by MegaHello** [comment]
ech
