### ISSUE TITLE
ssl addition

### ISSUE THREAD

**Issue by babdab9** [KibiiTV/weebshare#22]
people want it, add it

**Comment by GummiWummiBear** [comment]
Never™

**Comment by 0x0ade** [comment]
Assuming you're using CloudFlare:

![flick the switch](https://www.cloudflare.com/img/products/ssl/configuring-ssl-with-cloudflare.svg)

**Comment by binuwu** [comment]
It has been done!!!

**Comment by babdab9** [comment]
WWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
