### ISSUE TITLE
access request

### ISSUE THREAD

**Issue by shoodes** [KibiiTV/weebshare#24]
**hi am weeb l00king to upgrade sharex game from imgur to please.killl.me**

VERY Interested in this. Hope to provide feedback and my experiences using weebshare.
`Shades#4335`

**Comment by Shumatsu** [comment]
This is not what GitHub issues are for. You are on Discord server, ask there.

**Comment by shoodes** [comment]
readme said to open an issue here requesting access. 

but I might actually be wrong tbh

**Comment by Shumatsu** [comment]
Okay, it's too early for me to respond on issues...

**Comment by shoodes** [comment]
cheers, it's like 2 AM where I am right now so I wasn't confident in what I was reading either haha

**Comment by GummiWummiBear** [comment]
no you're right

**Comment by binuwu** [comment]
Will provide access, thanks for asking!
