### ISSUE TITLE
Existential Crisis

### ISSUE THREAD

**Issue by MetalRuller** [KibiiTV/weebshare#6]
You live life once and once it's gone you're a nothingness of once was one that is fucking rotting, and everyone is on edge because of it and it's personal.
Society think they're fucking normal and when confronted with truth, they become even corny and fucking shit, cringeworthy. Constantly deluded, thinking they'll get a girlfriend because you are kind you fucking delusional dipshits or because, you helped an elderly cross the road? GOOD ON YOU FUCKING DIPSHIT. GIRLS SUBCONSCIOUSLY SEEK THRILL. So you go hit the GYM, make a notable figure out of yourself.

**Comment by binuwu** [comment]
hi
