### ISSUE TITLE
Gachi isn't gay, it's manly.

### ISSUE THREAD

**Issue by MetalRuller** [KibiiTV/weebshare#8]
[https://www.youtube.com/playlist?list=PLLk3X9HhPRCtYeKg7_HovEZkridF_dvwr](https://www.youtube.com/playlist?list=PLLk3X9HhPRCtYeKg7_HovEZkridF_dvwr)

**Comment by babdab9** [comment]
S-T-O-P

**Comment by MetalRuller** [comment]
sotp

**Comment by MercerMrc** [comment]
i agree tbh

**Comment by MercerMrc** [comment]
close

**Comment by MercerMrc** [comment]
open
